//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Attachment
    {
        public long Id { get; set; }
        public int DocId { get; set; }
        public string AttachmentName { get; set; }
        public byte[] Attachment { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> DocType { get; set; }
    
        public virtual tb_Master tb_Master { get; set; }
    }
}
