//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PerlTambahan
    {
        public int Id { get; set; }
        public int SPKId { get; set; }
        public Nullable<int> No { get; set; }
        public string AdditionalItem { get; set; }
    }
}
