//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_spkHdr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_spkHdr()
        {
            this.tb_KetTambahan = new HashSet<tb_KetTambahan>();
        }
    
        public int Id { get; set; }
        public System.DateTime SPKDate { get; set; }
        public Nullable<System.DateTime> JanjiPenyerahan { get; set; }
        public string LOTNo { get; set; }
        public string Buyer { get; set; }
        public string BuyerAddress { get; set; }
        public string KTP { get; set; }
        public string Phone { get; set; }
        public string STNKName { get; set; }
        public string STNKAddress { get; set; }
        public string Email { get; set; }
        public string Branch { get; set; }
        public string Merk { get; set; }
        public string Warna { get; set; }
        public string Karoseri { get; set; }
        public string MachineNo { get; set; }
        public string RangkaNo { get; set; }
        public int Pembiayaan { get; set; }
        public string Via { get; set; }
        public Nullable<double> PercentageBunga { get; set; }
        public Nullable<double> OTRPrice { get; set; }
        public Nullable<double> KaroseriPrice { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<double> DP { get; set; }
        public string TandaJadi { get; set; }
        public string Pembayaran { get; set; }
        public string TransverVia { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string AlamatKirim { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<bool> IsKaroseri { get; set; }
        public string KaroseriDesc { get; set; }
        public Nullable<bool> IsOnTR { get; set; }
        public Nullable<bool> IsOffTR { get; set; }
        public Nullable<bool> IsChooseNo { get; set; }
        public string ChooseNo { get; set; }
    
        public virtual tb_Master tb_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_KetTambahan> tb_KetTambahan { get; set; }
    }
}
