//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_workflowSetting
    {
        public long Id { get; set; }
        public int HeaderID { get; set; }
        public int ApprovalLevel { get; set; }
        public string Actor { get; set; }
        public string ActorID { get; set; }
        public string Action { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string action_desc { get; set; }
    
        public virtual tb_workflowSettingHdr tb_workflowSettingHdr { get; set; }
    }
}
